import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { createServer } from 'http';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors({
  origin: ['http://localhost:5173', 'http://localhost:5174'],
  credentials: true
}));
app.use(express.json({ limit: '50mb' }));

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', message: 'Server is running' });
});

// OpenAI text analysis endpoint
app.post('/api/analyze-text', async (req, res) => {
  try {
    const { inputText, format } = req.body;
    
    if (!inputText || !format) {
      return res.status(400).json({ error: 'Missing required fields: inputText and format' });
    }

    const openaiApiKey = process.env.OPENAI_API_KEY;
    if (!openaiApiKey) {
      return res.status(500).json({ error: 'OpenAI API key not configured on server' });
    }

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openaiApiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: `You are an AI that helps convert text into visual learning formats for neurodiverse students. Based on the input text and selected format (${format}), provide a structured breakdown that can be used to create visual content. Return a JSON response with: title, description, and sections array containing the visual elements.`
          },
          {
            role: 'user',
            content: `Convert this text into a ${format} format: "${inputText}"`
          }
        ],
        max_tokens: 1000,
        temperature: 0.7
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('OpenAI API Error:', errorText);
      return res.status(response.status).json({ 
        error: `OpenAI API error: ${response.statusText}`,
        details: errorText
      });
    }

    const data = await response.json();
    const aiResponse = data.choices[0]?.message?.content;
    
    if (!aiResponse) {
      return res.status(500).json({ error: 'No content generated by OpenAI API' });
    }

    // Clean and parse the JSON response
    let cleanedText = aiResponse.replace(/```json\n?/g, '').replace(/```\n?/g, '');
    
    try {
      const parsed = JSON.parse(cleanedText);
      res.json(parsed);
    } catch (error) {
      // Fallback if parsing fails
      const titleMatch = aiResponse.match(/"title":\s*"([^"]+)"/);
      const title = titleMatch ? titleMatch[1] : `${format.charAt(0).toUpperCase() + format.slice(1)} - ${new Date().toLocaleDateString()}`;
      
      res.json({
        title: title,
        description: aiResponse,
        sections: []
      });
    }
  } catch (error) {
    console.error('Error in /api/analyze-text:', error);
    res.status(500).json({ 
      error: 'Internal server error',
      message: error.message 
    });
  }
});

// OpenAI DALL-E image generation endpoint
app.post('/api/generate-image', async (req, res) => {
  try {
    const { prompt, format } = req.body;
    
    if (!prompt || !format) {
      return res.status(400).json({ error: 'Missing required fields: prompt and format' });
    }

    const openaiApiKey = process.env.OPENAI_API_KEY;
    if (!openaiApiKey) {
      return res.status(500).json({ error: 'OpenAI API key not configured on server' });
    }

    // Generate multiple variations by making multiple requests
    const variations = [];
    
    for (let i = 0; i < 3; i++) {
      const response = await fetch('https://api.openai.com/v1/images/generations', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${openaiApiKey}`
        },
        body: JSON.stringify({
          model: 'dall-e-3',
          prompt: prompt,
          n: 1,
          size: '1024x1024',
          quality: 'standard',
          style: 'vivid'
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error(`DALL-E API Error (variation ${i + 1}):`, errorText);
        continue;
      }

      const data = await response.json();
      if (data.data && data.data[0]?.url) {
        variations.push({
          id: i + 1,
          url: data.data[0].url,
          seed: Math.floor(Math.random() * 1000000)
        });
      }
    }

    if (variations.length === 0) {
      return res.status(500).json({ error: 'Failed to generate any images' });
    }

    res.json({
      variations,
      message: `Generated ${variations.length} variation(s) using DALL-E 3`
    });
  } catch (error) {
    console.error('Error in /api/generate-image:', error);
    res.status(500).json({ 
      error: 'Internal server error',
      message: error.message 
    });
  }
});

const server = createServer(app);

server.listen(PORT, () => {
  console.log(`✅ Backend server running on http://localhost:${PORT}`);
  console.log(`📡 Ready to accept requests from frontend`);
});
